/**
 * Theme portado desde los mockups de la carpeta 'design/'.
 * Las medidas se expresan en rem sobre una base de 10px (html { font-size: 62.5% }).
 */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#ff8a5c',
        'tertiary-container': '#3a3a3e',
        tertiary: '#c9c9c4',
        'surface-dim': '#0E0E10',
        'surface-variant': '#2a2a2e',
        error: '#ff6b6b',
        secondary: '#FFC94A',
        'on-primary-fixed-variant': '#7a2f00',
        'inverse-on-surface': '#1A1A1E',
        'error-container': '#4a1414',
        'secondary-fixed-dim': '#FFC94A',
        'surface-bright': '#2e2e32',
        'on-primary-fixed': '#3a1200',
        'surface-container-highest': '#2a2a2e',
        'on-error-container': '#ffdad6',
        'surface-container-high': '#232326',
        'on-secondary': '#0E0E10',
        'secondary-container': '#FFC94A',
        'surface-container-lowest': '#000000',
        'on-tertiary': '#0E0E10',
        'on-secondary-fixed-variant': '#7a5c00',
        'surface-tint': '#FF6B35',
        'on-surface-variant': '#F5F5F0',
        surface: '#1A1A1E',
        'on-tertiary-fixed-variant': '#3a3a3e',
        'on-surface': '#F5F5F0',
        'on-tertiary-container': '#F5F5F0',
        'secondary-fixed': '#FFC94A',
        'primary-fixed': '#ffdbd0',
        'tertiary-fixed-dim': '#c9c9c4',
        'outline-variant': '#3a3a3e',
        'on-primary': '#0E0E10',
        'inverse-surface': '#F5F5F0',
        'inverse-primary': '#c9481f',
        'tertiary-fixed': '#e4e2e1',
        'on-tertiary-fixed': '#0E0E10',
        'primary-container': '#FF6B35',
        'on-background': '#F5F5F0',
        'on-secondary-container': '#0E0E10',
        'surface-container': '#19191c',
        background: '#0E0E10',
        'on-primary-container': '#ffffff',
        primary: '#FF6B35',
        'surface-container-low': '#161619',
        outline: '#5c5c5c',
        'on-secondary-fixed': '#0E0E10',
        'on-error': '#ffffff',
        success: '#7bd88f',
        'success-container': '#1e3a26',
        warning: '#FFC94A',
        'warning-container': '#3d2f0f',
      },
      borderRadius: {
        DEFAULT: '0.4rem',
        lg: '0.8rem',
        xl: '1.2rem',
        '2xl': '1.6rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '1.6rem',
        gutter: '2.4rem',
        'margin-desktop': '6.4rem',
        unit: '0.8rem',
      },
      maxWidth: {
        'container-max': '128rem',
      },
      fontFamily: {
        headline: ['Anton', 'Impact', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['1.2rem', { lineHeight: '1.6rem', fontWeight: '500' }],
        'label-bold': [
          '1.4rem',
          { lineHeight: '1.6rem', letterSpacing: '0.05em', fontWeight: '700' },
        ],
        'body-md': ['1.6rem', { lineHeight: '2.4rem', fontWeight: '400' }],
        'body-lg': ['1.8rem', { lineHeight: '2.8rem', fontWeight: '400' }],
        'headline-md': ['3.2rem', { lineHeight: '3.6rem', fontWeight: '400' }],
        'headline-lg-mobile': ['3.6rem', { lineHeight: '4rem', fontWeight: '400' }],
        'headline-lg': [
          '4.8rem',
          { lineHeight: '5.2rem', letterSpacing: '0.02em', fontWeight: '400' },
        ],
        'headline-xl': [
          '8rem',
          { lineHeight: '8rem', letterSpacing: '0.02em', fontWeight: '400' },
        ],
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(1.6rem)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-right': {
          from: { opacity: '0', transform: 'translateX(2.4rem)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-out',
        'slide-up': 'slide-up 0.35s ease-out',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
      },
    },
  },
  plugins: [],
};
